Document: vpn-util
Title: Debian vpn-util Manual
Author: <insert document author here>
Abstract: This manual describes what vpn-util is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vpn-util/vpn-util.sgml.gz

Format: postscript
Files: /usr/share/doc/vpn-util/vpn-util.ps.gz

Format: text
Files: /usr/share/doc/vpn-util/vpn-util.text.gz

Format: HTML
Index: /usr/share/doc/vpn-util/html/index.html
Files: /usr/share/doc/vpn-util/html/*.html
